<?php 

	$_code=$this->getMethodCode();
	
?>

<div>

<?php echo $this->getMethod()->getConfigData('message');

$hiddenbandeira = $_code."_check_cartaobandeira";

?>

</div>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="">
	
	<?php

		$json = array("meios_de_pagamento"=>array("correntista"=>array("api_key"=>$this->getMethod()->getConfigData('api_key'), 
																		"email"=>$this->getMethod()->getConfigData('email_gateway'))));
		$toJson = json_encode($json);

		$url = 'https://www.akatus.com/api/v1/meios-de-pagamento.json';
		#$url = 'https://dev.akatus.com/api/v1/meios-de-pagamento.json';
		$curl = curl_init();
		curl_setopt($curl, CURLOPT_URL,$url);
		#curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
		# curl_setopt($curl, CURLOPT_USERPWD, $user . ":" . $passwd);
		curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/4.0");
		curl_setopt($curl, CURLOPT_POST, true);
		curl_setopt($curl, CURLOPT_POSTFIELDS, $toJson);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		$retJson = curl_exec($curl);
		$errJson = curl_error($curl);

		Mage::Log("Erro de cURL:". $errJson);

		curl_close($curl);

		$retornoArray = json_decode($retJson);
		
		$meios = $retornoArray->resposta->meios_de_pagamento;

		foreach($meios as $meiopagamento){		


			if($meiopagamento->descricao=="Boleto Bancário"){
			Mage::Log("Mostrar boleto");

            echo "<li class='form_fields'>";

			echo "<li>
				  <!--<input type='radio' onClick='ffBoleto2();' value='boleto' name='forma' id='forma'  />-->
				  <input type='hidden' value='boleto' name='boletakatus' id='boletakatus'  />
				  <!--<span>".$meiopagamento->descricao.'</span>-->';
			
			} 
		
			echo "</li>";
	
		}/// fim do foreach
		
	?>	   
         
    <input title="<?php echo $this->__('Check Formapagamento:') ?>" name="payment[check_formapagamentoboleto]" type="hidden" id="<?php echo $_code ?>_check_formapagamentoboleto" value="boleto" />

</ul>

<script>
	function ffBoleto2(){
		document.getElementById("<?php echo $_code ?>_check_formapagamentoboleto").value="boleto";
		
		/*	
		var cc =  document.getElementById('cc');
		if(typeof(cc) != 'undefined' && cc != null)
		{
		  document.getElementById("cc").style.display="none";
		} 	

		var tef = document.getElementById('tef');
		if(typeof(tef) != 'undefined' && tef != null)
		{
		  document.getElementById("tef").style.display="none";
		}
		*/

		
	}
	
	
	var VALOR_COMPRA;
	function formatarNumero (rnum) {
		   return "R$ "+ formatamoeda(Math.round(rnum*Math.pow(10,2))/Math.pow(10,2));
	}
       
	function formatamoeda(num) {

		   x = 0;

		   if(num<0) {
		      num = Math.abs(num);
		      x = 1;
		   }

		   if(isNaN(num)) num = "0";
		      cents = Math.floor((num*100+0.5)%100);

		   num = Math.floor((num*100+0.5)/100).toString();

		   if(cents < 10) cents = "0" + cents;
		      for (var i = 0; i < Math.floor((num.length-(1+i))/3); i++)
		         num = num.substring(0,num.length-(4*i+3))+'.'
		               +num.substring(num.length-(4*i+3));

		   ret = num + ',' + cents;

		   if (x == 1) ret = ' - ' + ret;return ret;

		}
	
	function removeOpcoes(selectbox)
	{
		var i;
		for(i=selectbox.options.length-1;i>=0;i--)
		{
			selectbox.remove(i);
		}
	}	
	
        
        
        function selectBandeira2(bandeira){
            
           document.getElementById('<?php echo $_code ?>_check_cartaobandeira').value = bandeira;
           
           if(bandeira.length != 0){
               
                var newClass = "cc_inactive";
                var children = document.getElementById('cc_bandeiras').getElementsByTagName('img');

                for(var i = 0; i < children.length; i++){

                            var id = children[i].getAttribute("id");                            
                            var currDivElem = document.getElementById(id);
                            
                            if(id == bandeira){                                
                                currDivElem.setAttribute("class", "cc_active"); 
                                currDivElem.setAttribute("className", "cc_active");
                            } else {                            
                                currDivElem.setAttribute("class", "cc_inactive"); 
                                currDivElem.setAttribute("className", "cc_inactive");                                
                            }

                    }	
                    
           } else {
               alert('Vazio'); 
          }  
    
           
        
        }
       
</script>