<?php 

	$_code=$this->getMethodCode();
	
?>

<div>

<?php echo $this->getMethod()->getConfigData('message');

$hiddenbandeira = $_code."_check_cartaobandeira";

?>

</div>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="">
	
	<?php

		$json = array("meios_de_pagamento"=>array("correntista"=>array("api_key"=>$this->getMethod()->getConfigData('api_key'), 
																		"email"=>$this->getMethod()->getConfigData('email_gateway'))));
		$toJson = json_encode($json);

		$url = 'https://www.akatus.com/api/v1/meios-de-pagamento.json';
		#$url = 'https://dev.akatus.com/api/v1/meios-de-pagamento.json';
		$curl = curl_init();
		curl_setopt($curl, CURLOPT_URL,$url);
		curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/4.0");
		curl_setopt($curl, CURLOPT_POST, true);
		curl_setopt($curl, CURLOPT_POSTFIELDS, $toJson);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		$retJson = curl_exec($curl);
		$errJson = curl_error($curl);

		Mage::Log("Erro de cURL:". $errJson);

		curl_close($curl);

		$retornoArray = json_decode($retJson);
		
		$meios = $retornoArray->resposta->meios_de_pagamento;

		foreach($meios as $meiopagamento){		


			if( $meiopagamento->descricao=="TEF"){
			Mage::Log("Mostrar TEF");
				echo "<li>
						<!--<input onClick='ffTef2();' type='radio' value='".$meiopagamento->descricao."' name='forma' id='forma' disabled >-->
						<input type='hidden' value='".$meiopagamento->descricao."' name='forma' id='forma'>
						<!--<span>Cartao de Debito - ".$meiopagamento->descricao."</span>-->"; ?>
				
				<div style="display:block" id="tef" name="tef">       
					
					<table id="tablePay" cellspacing="5" style = 'margin-top:10px; '>
						<tbody>
							<tr>
								<td></td>
								<td>
									<label>
										<select  title="<?php echo $this->__('Check Tefbandeira:') ?>" style="width:250px;" name="payment[check_tefbandeira]" id="<?php echo $_code ?>_check_tefbandeira" class="input-text required-entry">
										<?php 
										$bandeiras= $meiopagamento->bandeiras ;
										foreach($bandeiras as $bandeira){ ?>
										  <option value="<?php echo $bandeira->codigo; ?>"><?php echo $bandeira->descricao; ?></option>
										<?php } ?>
										</select>
									</label>
								</td>
							</tr>  
						</tbody>
					</table> 
						
				</div>			
			
		<?php 
			
			} 


		
			echo "</li>";
	
		}/// fim do foreach
		
	?>	   
         
    <input title="<?php echo $this->__('Check Formapagamento:') ?>" name="payment[check_formapagamentotef]" type="hidden" id="<?php echo $_code ?>_check_formapagamentotef" value="tef" />

</ul>

<script>
	function ffTef2(){
		document.getElementById("akatustef_check_formapagamentotef").value="tef";
		
		
	}

	function formatarNumero (rnum) {
		   return "R$ "+ formatamoeda(Math.round(rnum*Math.pow(10,2))/Math.pow(10,2));
	}
       
	function formatamoeda(num) {

		   x = 0;

		   if(num<0) {
		      num = Math.abs(num);
		      x = 1;
		   }

		   if(isNaN(num)) num = "0";
		      cents = Math.floor((num*100+0.5)%100);

		   num = Math.floor((num*100+0.5)/100).toString();

		   if(cents < 10) cents = "0" + cents;
		      for (var i = 0; i < Math.floor((num.length-(1+i))/3); i++)
		         num = num.substring(0,num.length-(4*i+3))+'.'
		               +num.substring(num.length-(4*i+3));

		   ret = num + ',' + cents;

		   if (x == 1) ret = ' - ' + ret;return ret;

		}
	
	function removeOpcoes(selectbox)
	{
		var i;
		for(i=selectbox.options.length-1;i>=0;i--)
		{
			selectbox.remove(i);
		}
	}	
</script>